import {
  NOTE_C4_HZ,
  NOTE_D4_HZ,
  NOTE_E4_HZ,
  NOTE_F4_HZ,
  NOTE_G3_HZ,
  NOTE_G4_HZ,
} from '../../audio/notes'
import type { QuestDefinition } from '../../lessons/types'

export const catalog: QuestDefinition[] = [
  {
    id: 'trumpet-basics',
    order: 1,
    title: 'Познакомься с трубой',
    description: 'Найди основные части инструмента — осмотри трубу и отметь каждую деталь.',
    skill: 'Знание инструмента',
    xpReward: 50,
    type: 'checklist',
    config: {
      kind: 'checklist',
      data: {
        successLabel: 'Отлично, инструмент изучен!',
        items: [
          {
            id: 'mouthpiece',
            label: 'Мундштук',
            hint: 'Снимается и надевается на мундштучную трубку',
          },
          {
            id: 'leadpipe',
            label: 'Мундштучная трубка',
            hint: 'Первая трубка сразу после мундштука',
          },
          {
            id: 'valves',
            label: 'Вентили',
            hint: 'Три клапана посередине — нажимаются тремя пальцами правой руки',
          },
          {
            id: 'bell',
            label: 'Раструб',
            hint: 'Широкий конец трубы — звук выходит отсюда',
          },
        ],
      },
    },
  },
  {
    id: 'breathing',
    order: 2,
    title: 'Дыхание диафрагмой',
    description: 'Потренируй цикл вдох — задержка — выдох по схеме 4-2-6.',
    skill: 'Дыхание',
    xpReward: 60,
    type: 'breathing',
    unlockAfter: 'trumpet-basics',
  },
  {
    id: 'buzz',
    order: 3,
    title: 'Buzz без трубы',
    description: 'Сожми губы и издай устойчивый «бррр» — микрофон услышит твой buzz.',
    skill: 'Эмбушюра',
    xpReward: 70,
    type: 'buzz',
    unlockAfter: 'breathing',
  },
  {
    id: 'lip-warmup',
    order: 4,
    title: 'Разминка губ',
    description: 'Пройди чек-лист разминки перед игрой на инструменте.',
    skill: 'Разминка',
    xpReward: 50,
    type: 'lip-warmup',
    unlockAfter: 'buzz',
  },
  {
    id: 'mouthpiece',
    order: 5,
    title: 'Первый звук в мундштук',
    description: 'Издай устойчивый звук в мундштуке — микрофон засчитает секунду тона.',
    skill: 'Первый звук',
    xpReward: 80,
    type: 'mouthpiece',
    unlockAfter: 'lip-warmup',
  },
  {
    id: 'dynamics',
    order: 6,
    title: 'Тихо и громко',
    description: 'Сначала тихий звук, затем громкий — оцениваем силу, не высоту ноты.',
    skill: 'Контроль воздуха',
    xpReward: 60,
    type: 'dynamics',
    unlockAfter: 'mouthpiece',
  },
  {
    id: 'metronome-60',
    order: 7,
    title: 'Метроном 60 BPM',
    description: 'Нажимай в такт метроному — 8 долей, минимум 6 попаданий.',
    skill: 'Ритм',
    xpReward: 70,
    type: 'metronome',
    unlockAfter: 'dynamics',
  },
  {
    id: 'hold-c4',
    order: 8,
    title: 'Удержи «до»',
    description: 'Удержи ноту до (C4) в допуске ±80 центов в течение 2 секунд.',
    skill: 'Интонация',
    xpReward: 80,
    type: 'hold-note',
    unlockAfter: 'metronome-60',
  },
  {
    id: 'two-notes',
    order: 9,
    title: 'Два звука подряд',
    description: 'Сыграй до и ми по очереди — широкий допуск для новичков.',
    skill: 'Стабильность',
    xpReward: 90,
    type: 'two-notes',
    unlockAfter: 'hold-c4',
  },
  {
    id: 'daily-mini',
    order: 10,
    title: 'Мини-комплекс дня',
    description: 'Разминка, ритм и одна нота — короткий ежедневный урок.',
    skill: 'Ежедневная практика',
    xpReward: 100,
    type: 'daily-mini',
    unlockAfter: 'two-notes',
  },
  {
    id: 'pedal-intro',
    order: 11,
    title: 'Низкая дорога',
    description: 'Попробуй сыграть ниже «до» — педальный регистр, широкий допуск.',
    skill: 'Педальный регистр',
    xpReward: 70,
    type: 'pitch-hold',
    unlockAfter: 'daily-mini',
    config: {
      kind: 'pitch-hold',
      data: { label: 'Соль (G3)', hz: NOTE_G3_HZ, toleranceCents: 100, holdMs: 2000 },
    },
  },
  {
    id: 'sustained-3s',
    order: 12,
    title: 'Выдержанный звук 3 с',
    description: 'Удержи «до» три секунды — тренируем выносливость губ.',
    skill: 'Выносливость губ',
    xpReward: 80,
    type: 'pitch-hold',
    unlockAfter: 'pedal-intro',
    config: {
      kind: 'pitch-hold',
      data: { label: 'До (C4)', hz: NOTE_C4_HZ, toleranceCents: 80, holdMs: 3000 },
    },
  },
  {
    id: 'relax-reset',
    order: 13,
    title: 'Сброс напряжения',
    description: 'Buzz и спокойное дыхание — восстановление без оценки точности.',
    skill: 'Восстановление',
    xpReward: 50,
    type: 'checklist',
    unlockAfter: 'sustained-3s',
    config: {
      kind: 'checklist',
      data: {
        successLabel: 'Сброс завершён',
        items: [
          { id: 'breath', label: '3 цикла 4-2-6', hint: 'Медленное диафрагмальное дыхание', seconds: 45 },
          { id: 'buzz', label: '5 мягких buzz', hint: 'Без напряжения в подбородке', seconds: 30 },
          { id: 'shake', label: 'Встряхни плечи', hint: 'Расслабь шею и плечи', seconds: 10 },
        ],
      },
    },
  },
  {
    id: 'note-echo',
    order: 14,
    title: 'Повтори за наставником',
    description: 'Слушай эталон и повтори ноты на инструменте.',
    skill: 'Слух',
    xpReward: 90,
    type: 'note-echo',
    unlockAfter: 'relax-reset',
    config: {
      kind: 'note-echo',
      data: {
        toleranceCents: 90,
        holdMs: 1200,
        steps: [
          { label: 'До (C4)', toneNote: 'C4', hz: NOTE_C4_HZ },
          { label: 'Ми (E4)', toneNote: 'E4', hz: NOTE_E4_HZ },
        ],
      },
    },
  },
  {
    id: 'vocalise-1',
    order: 15,
    title: 'Первый вокализ',
    description: 'Три ноты вверх и вниз — мягкий вокализ для разминки.',
    skill: 'Вокализ',
    xpReward: 90,
    type: 'pitch-sequence',
    unlockAfter: 'note-echo',
    config: {
      kind: 'pitch-sequence',
      data: {
        toleranceCents: 80,
        holdMs: 1200,
        successLabel: 'Вокализ готов!',
        showStaff: true,
        steps: [
          { label: 'До (C4)', hz: NOTE_C4_HZ },
          { label: 'Ми (E4)', hz: NOTE_E4_HZ },
          { label: 'Соль (G4)', hz: NOTE_G4_HZ },
          { label: 'Ми (E4)', hz: NOTE_E4_HZ },
          { label: 'До (C4)', hz: NOTE_C4_HZ },
        ],
      },
    },
  },
  {
    id: 'slow-fast',
    order: 16,
    title: 'Медленно, потом быстрее',
    description: 'Два прохода метронома: 60 BPM, затем 80 BPM.',
    skill: 'Контраст темпов',
    xpReward: 80,
    type: 'slow-fast',
    unlockAfter: 'vocalise-1',
    config: {
      kind: 'slow-fast',
      data: {
        rounds: [
          { bpm: 60, totalBeats: 8, requiredHits: 5 },
          { bpm: 80, totalBeats: 8, requiredHits: 5 },
        ],
      },
    },
  },
  {
    id: 'interval-third',
    order: 17,
    title: 'Терция',
    description: 'Сыграй интервал до — ми с допуском ±70 центов.',
    skill: 'Интервал',
    xpReward: 90,
    type: 'pitch-sequence',
    unlockAfter: 'slow-fast',
    config: {
      kind: 'pitch-sequence',
      data: {
        toleranceCents: 70,
        holdMs: 1500,
        successLabel: 'Терция чистая!',
        steps: [
          { label: 'До (C4)', hz: NOTE_C4_HZ },
          { label: 'Ми (E4)', hz: NOTE_E4_HZ },
        ],
      },
    },
  },
  {
    id: 'legato-air',
    order: 18,
    title: 'Легато дыханием',
    description: 'Непрерывный выдох и плавный buzz — связность звука.',
    skill: 'Связность',
    xpReward: 70,
    type: 'checklist',
    unlockAfter: 'interval-third',
    config: {
      kind: 'checklist',
      data: {
        successLabel: 'Легато освоено!',
        items: [
          { id: 'exhale', label: 'Длинный выдох', hint: 'Ровный поток воздуха 8–10 секунд', seconds: 10 },
          { id: 'buzz', label: 'Buzz на выдохе', hint: 'Один непрерывный buzz без рывков', seconds: 15 },
          { id: 'rest', label: 'Пауза и повтор', hint: 'Отдохни и повтори ещё раз', seconds: 5 },
        ],
      },
    },
  },
  {
    id: 'rhythm-80',
    order: 19,
    title: 'Метроном 80 BPM',
    description: 'Тап в такт 80 BPM — 8 долей, минимум 5 попаданий.',
    skill: 'Ритм + звук',
    xpReward: 80,
    type: 'metronome',
    unlockAfter: 'legato-air',
    config: {
      kind: 'metronome',
      data: { bpm: 80, totalBeats: 8, requiredHits: 5 },
    },
  },
  {
    id: 'register-mid',
    order: 20,
    title: 'Средний регистр',
    description: 'Удержи «соль» в среднем регистре.',
    skill: 'Регистр',
    xpReward: 90,
    type: 'pitch-hold',
    unlockAfter: 'rhythm-80',
    config: {
      kind: 'pitch-hold',
      data: { label: 'Соль (G4)', hz: NOTE_G4_HZ, toleranceCents: 75, holdMs: 2000 },
    },
  },
  {
    id: 'check-in',
    order: 21,
    title: 'Как твои губы?',
    description: 'Самооценка и лёгкая разминка — осознанная практика.',
    skill: 'Осознанность',
    xpReward: 50,
    type: 'checklist',
    unlockAfter: 'register-mid',
    config: {
      kind: 'checklist',
      data: {
        successLabel: 'Отлично, слушай тело!',
        items: [
          { id: 'feel', label: 'Оцени усталость губ', hint: 'От 1 (свежо) до 5 (устал) — запомни число' },
          { id: 'massage', label: 'Массаж губ', hint: '30 секунд лёгкого массажа', seconds: 30 },
          { id: 'water', label: 'Глоток воды', hint: 'Увлажни губы перед игрой' },
        ],
      },
    },
  },
  {
    id: 'complex-warmup',
    order: 22,
    title: 'Разминка комплекса',
    description: 'Три шага разминки перед полным комплексом дня.',
    skill: 'Разминка',
    xpReward: 60,
    type: 'checklist',
    unlockAfter: 'check-in',
    config: {
      kind: 'checklist',
      data: {
        successLabel: 'Разминка комплекса готова!',
        items: [
          { id: 'lips', label: 'Разминка губ', hint: '«Раз-раз» и лёгкий массаж', seconds: 30 },
          { id: 'buzz', label: 'Buzz в мундштук', hint: '5 спокойных buzz', seconds: 30 },
          { id: 'breath', label: 'Дыхание 4-2-6', hint: 'Два цикла перед игрой', seconds: 24 },
        ],
      },
    },
  },
  {
    id: 'complex-vocalise',
    order: 23,
    title: 'Вокализ комплекса',
    description: 'Четыре ноты по нотам на экране — вокализ комплекса.',
    skill: 'Вокализ',
    xpReward: 90,
    type: 'pitch-sequence',
    unlockAfter: 'complex-warmup',
    config: {
      kind: 'pitch-sequence',
      data: {
        toleranceCents: 75,
        holdMs: 1200,
        successLabel: 'Вокализ комплекса!',
        showStaff: true,
        steps: [
          { label: 'До (C4)', hz: NOTE_C4_HZ },
          { label: 'Ре (D4)', hz: NOTE_D4_HZ },
          { label: 'Ми (E4)', hz: NOTE_E4_HZ },
          { label: 'Фа (F4)', hz: NOTE_F4_HZ },
        ],
      },
    },
  },
  {
    id: 'complex-sequence',
    order: 24,
    title: 'Секвенция 4 нот',
    description: 'Пошаговое проигрывание короткой секвенции.',
    skill: 'Секвенция',
    xpReward: 100,
    type: 'pitch-sequence',
    unlockAfter: 'complex-vocalise',
    config: {
      kind: 'pitch-sequence',
      data: {
        toleranceCents: 70,
        holdMs: 1000,
        successLabel: 'Секвенция сыграна!',
        showStaff: true,
        steps: [
          { label: 'До (C4)', hz: NOTE_C4_HZ },
          { label: 'Ми (E4)', hz: NOTE_E4_HZ },
          { label: 'Соль (G4)', hz: NOTE_G4_HZ },
          { label: 'Ми (E4)', hz: NOTE_E4_HZ },
        ],
      },
    },
  },
  {
    id: 'full-complex-1',
    order: 25,
    title: 'Комплекс дня №1',
    description: 'Разминка → вокализ → секвенция — полный комплекс по структуре методики.',
    skill: 'Комплекс',
    xpReward: 120,
    type: 'complex-flow',
    unlockAfter: 'complex-sequence',
    config: {
      kind: 'complex-flow',
      data: {
        warmup: {
          successLabel: 'Разминка готова — к вокализу!',
          items: [
            { id: 'lips', label: 'Разминка губ', hint: '30 секунд', seconds: 30 },
            { id: 'buzz', label: 'Buzz', hint: '5 раз', seconds: 25 },
          ],
        },
        sequence: {
          toleranceCents: 75,
          holdMs: 1200,
          successLabel: 'Комплекс дня завершён!',
          showStaff: true,
          steps: [
            { label: 'До (C4)', hz: NOTE_C4_HZ },
            { label: 'Ре (D4)', hz: NOTE_D4_HZ },
            { label: 'Ми (E4)', hz: NOTE_E4_HZ },
            { label: 'Фа (F4)', hz: NOTE_F4_HZ },
          ],
        },
      },
    },
  },
  {
    id: 'streak-7',
    order: 26,
    title: '7 дней подряд',
    description: 'Играй 7 дней подряд — награда за постоянство.',
    skill: 'Мотивация',
    xpReward: 100,
    type: 'streak-gate',
    unlockAfter: 'full-complex-1',
    config: { kind: 'streak-gate', data: { minStreak: 7 } },
  },
  {
    id: 'dynamics-2',
    order: 27,
    title: 'Crescendo',
    description: 'От тихого к громкому — 5 ступеней нарастания.',
    skill: 'Динамика',
    xpReward: 80,
    type: 'crescendo',
    unlockAfter: 'streak-7',
    config: { kind: 'crescendo', data: { steps: 5 } },
  },
  {
    id: 'review-weak',
    order: 28,
    title: 'Повтор слабого места',
    description: 'Наставник предлагает повторить базовый квест.',
    skill: 'Повторение',
    xpReward: 60,
    type: 'review-weak',
    unlockAfter: 'dynamics-2',
    config: { kind: 'review-weak', data: {} },
  },
  {
    id: 'path-four-notes',
    order: 29,
    title: 'Путь из 4 нот',
    description: 'Мини-мелодия до-ре-ми-фа.',
    skill: 'Мелодия',
    xpReward: 110,
    type: 'pitch-sequence',
    unlockAfter: 'review-weak',
    config: {
      kind: 'pitch-sequence',
      data: {
        toleranceCents: 70,
        holdMs: 1000,
        successLabel: 'Путь пройден!',
        showStaff: true,
        steps: [
          { label: 'До (C4)', hz: NOTE_C4_HZ },
          { label: 'Ре (D4)', hz: NOTE_D4_HZ },
          { label: 'Ми (E4)', hz: NOTE_E4_HZ },
          { label: 'Фа (F4)', hz: NOTE_F4_HZ },
        ],
      },
    },
  },
  {
    id: 'first-melody',
    order: 30,
    title: 'Первая мелодия',
    description: 'Восемь нот — финальный квест месяца и бейдж трубача.',
    skill: 'Творчество',
    xpReward: 150,
    type: 'pitch-sequence',
    unlockAfter: 'path-four-notes',
    config: {
      kind: 'pitch-sequence',
      data: {
        toleranceCents: 65,
        holdMs: 900,
        successLabel: 'Первая мелодия — ты трубач!',
        showStaff: true,
        steps: [
          { label: 'До (C4)', hz: NOTE_C4_HZ },
          { label: 'Ре (D4)', hz: NOTE_D4_HZ },
          { label: 'Ми (E4)', hz: NOTE_E4_HZ },
          { label: 'Фа (F4)', hz: NOTE_F4_HZ },
          { label: 'Соль (G4)', hz: NOTE_G4_HZ },
          { label: 'Фа (F4)', hz: NOTE_F4_HZ },
          { label: 'Ми (E4)', hz: NOTE_E4_HZ },
          { label: 'До (C4)', hz: NOTE_C4_HZ },
        ],
      },
    },
  },
]

