export const strings = {
  appName: 'Трубач на коне',
  questMap: 'Карта квестов',
  questRangeLabel: 'Квесты',
  backToMap: 'К карте',
  questCompleted: 'Квест пройден!',
  questInDevelopment: 'Квест в разработке.',
  returnToMap: 'Вернуться на карту',
  xpGained: (xp: number) => `+${xp} XP`,
  level: 'Уровень',
  streak: 'Дни подряд',
  streakDays: (days: number) => `${days} ${days === 1 ? 'день' : days < 5 ? 'дня' : 'дней'}`,
  locked: 'Сначала пройди предыдущий квест',
  mascotQuestIntro: (title: string) => `Квест «${title}». Не спеши — главное качество, не скорость.`,
  mascotQuestDone: 'Отлично! Ещё один шаг к первой мелодии.',
  heroTitle: 'Добро пожаловать в путешествие трубача',
  heroLead:
    'Привет! Короткие квесты каждый день — от первого buzz до первой мелодии. Не спеши, главное качество.',
  heroCtaAbout: 'Как это работает',
  marqueeItems: [
    'трубач на коне',
    'практика каждый день',
    'шаг за шагом',
    'сначала слушай',
    'ищи свой звук',
    'дыши — и дуй',
    'качество важнее скорости',
    'одна нота за раз',
    'держи ритм',
    'тишина между нотами',
    'без отмазок — только дуй',
    'грязная практика — чистый звук',
  ],
  footerAbout: 'О проекте',
  footerCopyright: (year: number) =>
    `© ${year} Aleksey Kerkin. Трубач на коне. Не является официальным изданием методики Докшицера.`,
  weekProgress: (done: number, total: number) => `${done} из ${total} квестов`,
  loading: 'Загрузка…',
  langSwitchLabel: 'Язык',
  langRu: 'RU',
  langEn: 'EN',
  noteStaffAriaLabel: 'Нотный стан',
  resetProgress: 'Сбросить прогресс',
  resetProgressConfirmTitle: 'Сбросить прогресс?',
  resetProgressConfirmMessage:
    'Все пройденные квесты, XP и дни подряд будут сброшены. Это нельзя отменить.',
  resetProgressConfirm: 'Сбросить',
  cancel: 'Отмена',
} as const
