import {
  NOTE_C4_HZ,
  NOTE_D4_HZ,
  NOTE_E4_HZ,
  NOTE_F4_HZ,
  NOTE_G3_HZ,
  NOTE_G4_HZ,
} from '../../audio/notes'
import type { QuestDefinition } from '../../lessons/types'

export const catalog: QuestDefinition[] = [
  {
    id: 'trumpet-basics',
    order: 1,
    title: 'Meet the Trumpet',
    description: 'Find the main parts of the instrument — inspect the trumpet and mark each part.',
    skill: 'Instrument Knowledge',
    xpReward: 50,
    type: 'checklist',
    config: {
      kind: 'checklist',
      data: {
        successLabel: 'Great, instrument explored!',
        items: [
          {
            id: 'mouthpiece',
            label: 'Mouthpiece',
            hint: 'Removes and attaches to the leadpipe',
          },
          {
            id: 'leadpipe',
            label: 'Leadpipe',
            hint: 'The first tube right after the mouthpiece',
          },
          {
            id: 'valves',
            label: 'Valves',
            hint: 'Three valves in the middle — pressed with three fingers of the right hand',
          },
          {
            id: 'bell',
            label: 'Bell',
            hint: 'The wide end of the trumpet — sound comes out here',
          },
        ],
      },
    },
  },
  {
    id: 'breathing',
    order: 2,
    title: 'Diaphragmatic Breathing',
    description: 'Practice the inhale — hold — exhale cycle using the 4-2-6 pattern.',
    skill: 'Breathing',
    xpReward: 60,
    type: 'breathing',
    unlockAfter: 'trumpet-basics',
  },
  {
    id: 'buzz',
    order: 3,
    title: 'Buzz Without the Trumpet',
    description: 'Press your lips together and make a steady "brrr" — the microphone will hear your buzz.',
    skill: 'Embouchure',
    xpReward: 70,
    type: 'buzz',
    unlockAfter: 'breathing',
  },
  {
    id: 'lip-warmup',
    order: 4,
    title: 'Lip Warm-up',
    description: 'Complete the warm-up checklist before playing the instrument.',
    skill: 'Warm-up',
    xpReward: 50,
    type: 'lip-warmup',
    unlockAfter: 'buzz',
  },
  {
    id: 'mouthpiece',
    order: 5,
    title: 'First Sound in the Mouthpiece',
    description: 'Produce a steady sound in the mouthpiece — the microphone will count one second of tone.',
    skill: 'First Sound',
    xpReward: 80,
    type: 'mouthpiece',
    unlockAfter: 'lip-warmup',
  },
  {
    id: 'dynamics',
    order: 6,
    title: 'Soft and Loud',
    description: 'First a soft sound, then a loud one — we evaluate strength, not pitch.',
    skill: 'Air Control',
    xpReward: 60,
    type: 'dynamics',
    unlockAfter: 'mouthpiece',
  },
  {
    id: 'metronome-60',
    order: 7,
    title: 'Metronome 60 BPM',
    description: 'Tap in time with the metronome — 8 beats, at least 6 hits.',
    skill: 'Rhythm',
    xpReward: 70,
    type: 'metronome',
    unlockAfter: 'dynamics',
  },
  {
    id: 'hold-c4',
    order: 8,
    title: 'Hold C',
    description: 'Hold the note C (C4) within ±80 cents tolerance for 2 seconds.',
    skill: 'Intonation',
    xpReward: 80,
    type: 'hold-note',
    unlockAfter: 'metronome-60',
  },
  {
    id: 'two-notes',
    order: 9,
    title: 'Two Sounds in a Row',
    description: 'Play C and E in sequence — wide tolerance for beginners.',
    skill: 'Stability',
    xpReward: 90,
    type: 'two-notes',
    unlockAfter: 'hold-c4',
  },
  {
    id: 'daily-mini',
    order: 10,
    title: 'Daily Mini Routine',
    description: 'Warm-up, rhythm, and one note — a short daily lesson.',
    skill: 'Daily Practice',
    xpReward: 100,
    type: 'daily-mini',
    unlockAfter: 'two-notes',
  },
  {
    id: 'pedal-intro',
    order: 11,
    title: 'The Low Road',
    description: 'Try playing below C — pedal register, wide tolerance.',
    skill: 'Pedal Register',
    xpReward: 70,
    type: 'pitch-hold',
    unlockAfter: 'daily-mini',
    config: {
      kind: 'pitch-hold',
      data: { label: 'G (G3)', hz: NOTE_G3_HZ, toleranceCents: 100, holdMs: 2000 },
    },
  },
  {
    id: 'sustained-3s',
    order: 12,
    title: 'Sustained Sound 3 s',
    description: 'Hold C for three seconds — building lip endurance.',
    skill: 'Lip Endurance',
    xpReward: 80,
    type: 'pitch-hold',
    unlockAfter: 'pedal-intro',
    config: {
      kind: 'pitch-hold',
      data: { label: 'C (C4)', hz: NOTE_C4_HZ, toleranceCents: 80, holdMs: 3000 },
    },
  },
  {
    id: 'relax-reset',
    order: 13,
    title: 'Release Tension',
    description: 'Buzz and calm breathing — recovery without accuracy scoring.',
    skill: 'Recovery',
    xpReward: 50,
    type: 'checklist',
    unlockAfter: 'sustained-3s',
    config: {
      kind: 'checklist',
      data: {
        successLabel: 'Reset complete',
        items: [
          { id: 'breath', label: '3 cycles 4-2-6', hint: 'Slow diaphragmatic breathing', seconds: 45 },
          { id: 'buzz', label: '5 gentle buzzes', hint: 'No tension in your chin', seconds: 30 },
          { id: 'shake', label: 'Shake your shoulders', hint: 'Relax your neck and shoulders', seconds: 10 },
        ],
      },
    },
  },
  {
    id: 'note-echo',
    order: 14,
    title: 'Echo the Mentor',
    description: 'Listen to the reference and repeat the notes on your instrument.',
    skill: 'Ear Training',
    xpReward: 90,
    type: 'note-echo',
    unlockAfter: 'relax-reset',
    config: {
      kind: 'note-echo',
      data: {
        toleranceCents: 90,
        holdMs: 1200,
        steps: [
          { label: 'C (C4)', toneNote: 'C4', hz: NOTE_C4_HZ },
          { label: 'E (E4)', toneNote: 'E4', hz: NOTE_E4_HZ },
        ],
      },
    },
  },
  {
    id: 'vocalise-1',
    order: 15,
    title: 'First Vocalise',
    description: 'Three notes up and down — a gentle vocalise for warm-up.',
    skill: 'Vocalise',
    xpReward: 90,
    type: 'pitch-sequence',
    unlockAfter: 'note-echo',
    config: {
      kind: 'pitch-sequence',
      data: {
        toleranceCents: 80,
        holdMs: 1200,
        successLabel: 'Vocalise complete!',
        showStaff: true,
        steps: [
          { label: 'C (C4)', hz: NOTE_C4_HZ },
          { label: 'E (E4)', hz: NOTE_E4_HZ },
          { label: 'G (G4)', hz: NOTE_G4_HZ },
          { label: 'E (E4)', hz: NOTE_E4_HZ },
          { label: 'C (C4)', hz: NOTE_C4_HZ },
        ],
      },
    },
  },
  {
    id: 'slow-fast',
    order: 16,
    title: 'Slow, Then Faster',
    description: 'Two metronome passes: 60 BPM, then 80 BPM.',
    skill: 'Tempo Contrast',
    xpReward: 80,
    type: 'slow-fast',
    unlockAfter: 'vocalise-1',
    config: {
      kind: 'slow-fast',
      data: {
        rounds: [
          { bpm: 60, totalBeats: 8, requiredHits: 5 },
          { bpm: 80, totalBeats: 8, requiredHits: 5 },
        ],
      },
    },
  },
  {
    id: 'interval-third',
    order: 17,
    title: 'Third',
    description: 'Play the interval C — E with ±70 cents tolerance.',
    skill: 'Interval',
    xpReward: 90,
    type: 'pitch-sequence',
    unlockAfter: 'slow-fast',
    config: {
      kind: 'pitch-sequence',
      data: {
        toleranceCents: 70,
        holdMs: 1500,
        successLabel: 'Clean third!',
        steps: [
          { label: 'C (C4)', hz: NOTE_C4_HZ },
          { label: 'E (E4)', hz: NOTE_E4_HZ },
        ],
      },
    },
  },
  {
    id: 'legato-air',
    order: 18,
    title: 'Legato with Air',
    description: 'Continuous exhale and smooth buzz — connected sound.',
    skill: 'Connection',
    xpReward: 70,
    type: 'checklist',
    unlockAfter: 'interval-third',
    config: {
      kind: 'checklist',
      data: {
        successLabel: 'Legato mastered!',
        items: [
          { id: 'exhale', label: 'Long exhale', hint: 'Steady airflow for 8–10 seconds', seconds: 10 },
          { id: 'buzz', label: 'Buzz on exhale', hint: 'One continuous buzz without breaks', seconds: 15 },
          { id: 'rest', label: 'Pause and repeat', hint: 'Rest and do it again', seconds: 5 },
        ],
      },
    },
  },
  {
    id: 'rhythm-80',
    order: 19,
    title: 'Metronome 80 BPM',
    description: 'Tap in time at 80 BPM — 8 beats, at least 5 hits.',
    skill: 'Rhythm + Sound',
    xpReward: 80,
    type: 'metronome',
    unlockAfter: 'legato-air',
    config: {
      kind: 'metronome',
      data: { bpm: 80, totalBeats: 8, requiredHits: 5 },
    },
  },
  {
    id: 'register-mid',
    order: 20,
    title: 'Middle Register',
    description: 'Hold G in the middle register.',
    skill: 'Register',
    xpReward: 90,
    type: 'pitch-hold',
    unlockAfter: 'rhythm-80',
    config: {
      kind: 'pitch-hold',
      data: { label: 'G (G4)', hz: NOTE_G4_HZ, toleranceCents: 75, holdMs: 2000 },
    },
  },
  {
    id: 'check-in',
    order: 21,
    title: 'How Are Your Lips?',
    description: 'Self-assessment and light warm-up — mindful practice.',
    skill: 'Mindfulness',
    xpReward: 50,
    type: 'checklist',
    unlockAfter: 'register-mid',
    config: {
      kind: 'checklist',
      data: {
        successLabel: 'Great, listen to your body!',
        items: [
          { id: 'feel', label: 'Rate lip fatigue', hint: 'From 1 (fresh) to 5 (tired) — remember the number' },
          { id: 'massage', label: 'Lip massage', hint: '30 seconds of gentle massage', seconds: 30 },
          { id: 'water', label: 'Sip of water', hint: 'Moisten your lips before playing' },
        ],
      },
    },
  },
  {
    id: 'complex-warmup',
    order: 22,
    title: 'Routine Warm-up',
    description: 'Three warm-up steps before the full daily routine.',
    skill: 'Warm-up',
    xpReward: 60,
    type: 'checklist',
    unlockAfter: 'check-in',
    config: {
      kind: 'checklist',
      data: {
        successLabel: 'Routine warm-up ready!',
        items: [
          { id: 'lips', label: 'Lip warm-up', hint: '"One-two" and gentle massage', seconds: 30 },
          { id: 'buzz', label: 'Buzz in mouthpiece', hint: '5 calm buzzes', seconds: 30 },
          { id: 'breath', label: '4-2-6 breathing', hint: 'Two cycles before playing', seconds: 24 },
        ],
      },
    },
  },
  {
    id: 'complex-vocalise',
    order: 23,
    title: 'Routine Vocalise',
    description: 'Four notes as shown on screen — routine vocalise.',
    skill: 'Vocalise',
    xpReward: 90,
    type: 'pitch-sequence',
    unlockAfter: 'complex-warmup',
    config: {
      kind: 'pitch-sequence',
      data: {
        toleranceCents: 75,
        holdMs: 1200,
        successLabel: 'Routine vocalise!',
        showStaff: true,
        steps: [
          { label: 'C (C4)', hz: NOTE_C4_HZ },
          { label: 'D (D4)', hz: NOTE_D4_HZ },
          { label: 'E (E4)', hz: NOTE_E4_HZ },
          { label: 'F (F4)', hz: NOTE_F4_HZ },
        ],
      },
    },
  },
  {
    id: 'complex-sequence',
    order: 24,
    title: '4-Note Sequence',
    description: 'Step-by-step playback of a short sequence.',
    skill: 'Sequence',
    xpReward: 100,
    type: 'pitch-sequence',
    unlockAfter: 'complex-vocalise',
    config: {
      kind: 'pitch-sequence',
      data: {
        toleranceCents: 70,
        holdMs: 1000,
        successLabel: 'Sequence played!',
        showStaff: true,
        steps: [
          { label: 'C (C4)', hz: NOTE_C4_HZ },
          { label: 'E (E4)', hz: NOTE_E4_HZ },
          { label: 'G (G4)', hz: NOTE_G4_HZ },
          { label: 'E (E4)', hz: NOTE_E4_HZ },
        ],
      },
    },
  },
  {
    id: 'full-complex-1',
    order: 25,
    title: 'Daily Routine #1',
    description: 'Warm-up → vocalise → sequence — full routine following the method structure.',
    skill: 'Routine',
    xpReward: 120,
    type: 'complex-flow',
    unlockAfter: 'complex-sequence',
    config: {
      kind: 'complex-flow',
      data: {
        warmup: {
          successLabel: 'Warm-up done — on to vocalise!',
          items: [
            { id: 'lips', label: 'Lip warm-up', hint: '30 seconds', seconds: 30 },
            { id: 'buzz', label: 'Buzz', hint: '5 times', seconds: 25 },
          ],
        },
        sequence: {
          toleranceCents: 75,
          holdMs: 1200,
          successLabel: 'Daily routine complete!',
          showStaff: true,
          steps: [
            { label: 'C (C4)', hz: NOTE_C4_HZ },
            { label: 'D (D4)', hz: NOTE_D4_HZ },
            { label: 'E (E4)', hz: NOTE_E4_HZ },
            { label: 'F (F4)', hz: NOTE_F4_HZ },
          ],
        },
      },
    },
  },
  {
    id: 'streak-7',
    order: 26,
    title: '7-Day Streak',
    description: 'Play 7 days in a row — reward for consistency.',
    skill: 'Motivation',
    xpReward: 100,
    type: 'streak-gate',
    unlockAfter: 'full-complex-1',
    config: { kind: 'streak-gate', data: { minStreak: 7 } },
  },
  {
    id: 'dynamics-2',
    order: 27,
    title: 'Crescendo',
    description: 'From soft to loud — 5 steps of growth.',
    skill: 'Dynamics',
    xpReward: 80,
    type: 'crescendo',
    unlockAfter: 'streak-7',
    config: { kind: 'crescendo', data: { steps: 5 } },
  },
  {
    id: 'review-weak',
    order: 28,
    title: 'Review Weak Spot',
    description: 'The mentor suggests repeating a basic quest.',
    skill: 'Review',
    xpReward: 60,
    type: 'review-weak',
    unlockAfter: 'dynamics-2',
    config: { kind: 'review-weak', data: {} },
  },
  {
    id: 'path-four-notes',
    order: 29,
    title: 'Path of 4 Notes',
    description: 'Mini-melody C-D-E-F.',
    skill: 'Melody',
    xpReward: 110,
    type: 'pitch-sequence',
    unlockAfter: 'review-weak',
    config: {
      kind: 'pitch-sequence',
      data: {
        toleranceCents: 70,
        holdMs: 1000,
        successLabel: 'Path complete!',
        showStaff: true,
        steps: [
          { label: 'C (C4)', hz: NOTE_C4_HZ },
          { label: 'D (D4)', hz: NOTE_D4_HZ },
          { label: 'E (E4)', hz: NOTE_E4_HZ },
          { label: 'F (F4)', hz: NOTE_F4_HZ },
        ],
      },
    },
  },
  {
    id: 'first-melody',
    order: 30,
    title: 'First Melody',
    description: 'Eight notes — the month\'s final quest and trumpeter badge.',
    skill: 'Creativity',
    xpReward: 150,
    type: 'pitch-sequence',
    unlockAfter: 'path-four-notes',
    config: {
      kind: 'pitch-sequence',
      data: {
        toleranceCents: 65,
        holdMs: 900,
        successLabel: 'First melody — you\'re a trumpeter!',
        showStaff: true,
        steps: [
          { label: 'C (C4)', hz: NOTE_C4_HZ },
          { label: 'D (D4)', hz: NOTE_D4_HZ },
          { label: 'E (E4)', hz: NOTE_E4_HZ },
          { label: 'F (F4)', hz: NOTE_F4_HZ },
          { label: 'G (G4)', hz: NOTE_G4_HZ },
          { label: 'F (F4)', hz: NOTE_F4_HZ },
          { label: 'E (E4)', hz: NOTE_E4_HZ },
          { label: 'C (C4)', hz: NOTE_C4_HZ },
        ],
      },
    },
  },
]
