export const strings = {
  appName: 'Trumpeter on Horseback',
  questMap: 'Quest map',
  questRangeLabel: 'Quests',
  backToMap: 'Back to map',
  startQuest: 'Start quest',
  completeQuest: 'Complete quest',
  questCompleted: 'Quest complete!',
  questInDevelopment: 'Quest in development.',
  returnToMap: 'Return to map',
  xpGained: (xp: number) => `+${xp} XP`,
  level: 'Level',
  streak: 'Streak',
  streakDays: (days: number) => `${days} ${days === 1 ? 'day' : 'days'}`,
  locked: 'Complete the previous quest first',
  mascotQuestIntro: (title: string) => `Quest “${title}”. Take your time — quality over speed.`,
  mascotQuestDone: 'Great! One more step toward your first melody.',
  heroTitle: 'Welcome to the trumpeter’s journey',
  heroLead:
    'Hi! Short quests every day — from your first buzz to your first melody. No rush, quality first.',
  heroCtaAbout: 'How it works',
  marqueeItems: [
    'trumpeter on horseback',
    'practice every day',
    'step by step',
    'listen first',
    'find your sound',
    'breathe — then blow',
    'quality over speed',
    'one note at a time',
    'stay in the groove',
    'space between the notes',
    'no excuses — just blow',
    'ugly practice — clean tone',
  ],
  footerAbout: 'About',
  footerCopyright: '© Trumpeter on Horseback — educational project',
  weekProgress: (done: number, total: number) => `${done} of ${total} quests`,
  loading: 'Loading…',
  langSwitchLabel: 'Language',
  langRu: 'RU',
  langEn: 'EN',
  noteStaffAriaLabel: 'Music staff',
  resetProgress: 'Reset progress',
  resetProgressConfirmTitle: 'Reset progress?',
  resetProgressConfirmMessage:
    'All completed quests, XP, and streak will be cleared. This cannot be undone.',
  resetProgressConfirm: 'Reset',
  cancel: 'Cancel',
} as const
